apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aunpvc1
spec:
  storageClassName: minikubestorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-storage
spec:
  storageClassName: minikubestorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/arun/"
    type: DirectoryOrCreate
