apiVersion: v1
kind: Service
metadata:
  name: test-name
  namespace: test-ns
spec:
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test-name
  namespace: test-ns
subsets:
  - addresses:
      - ip: 192.168.32.54
    ports:
      - port: 1122
